[[libxlsxwriter]]
arch = "aarch64"
git-tree-sha1 = "04df028ead158baac9aa961708d675377d305243"
os = "macos"

    [[libxlsxwriter.download]]
    sha256 = "03ac25db1bf2e339591bcc986e9b38c31cf14591b741c075339ede885dac1243"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.aarch64-apple-darwin.tar.gz"
[[libxlsxwriter]]
arch = "aarch64"
git-tree-sha1 = "28ed05f83fc4134c682ff4b9eb111354d7cfd5b9"
libc = "glibc"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "8ecea85bbfa0799a18fb256090ddc792753a77f0d4d9ef697544482e704a4ced"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.aarch64-linux-gnu.tar.gz"
[[libxlsxwriter]]
arch = "aarch64"
git-tree-sha1 = "ededfef5acfdcf8ffc74a01da777d24ebea8d98e"
libc = "musl"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "f69c060c88aa41cd3226c629fa4be2713b08d93514b3d29712da8492eeb2e905"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.aarch64-linux-musl.tar.gz"
[[libxlsxwriter]]
arch = "aarch64"
git-tree-sha1 = "84c1f1b4fa8ce3a3ae400228a85d0c50c915b621"
os = "freebsd"

    [[libxlsxwriter.download]]
    sha256 = "695a6cd36fd2f1ec8cdc1e2b3139266cd0dbdce0b0d464c394476451e437a19b"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.aarch64-unknown-freebsd.tar.gz"
[[libxlsxwriter]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e01cb42f88e1565270569bc0acced1a17cf68596"
libc = "glibc"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "3597b814838da53aea441e7951c41e98fb5f285990b24651961492c7795a3c46"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.armv6l-linux-gnueabihf.tar.gz"
[[libxlsxwriter]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fd6917caa6a1aa0f1e11184f462094793d171e78"
libc = "musl"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "6ffe979c4ed0e5373c62604622c53e9c9316a6e89cec235d99eaa106f2201934"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.armv6l-linux-musleabihf.tar.gz"
[[libxlsxwriter]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "acae6cf7093214748b4f51d0d0d719e7cbb2e388"
libc = "glibc"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "59cf9ab268d7413b062ed018a178ee2162ba5ae877d0d3e30ddc19834325e5ce"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.armv7l-linux-gnueabihf.tar.gz"
[[libxlsxwriter]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "430c1616463f56ff46a594a4621936880562e6c3"
libc = "musl"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "c52a55fc37e86bf22470a0240ef3036532039c305ded44032abe51bce348cc7f"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.armv7l-linux-musleabihf.tar.gz"
[[libxlsxwriter]]
arch = "i686"
git-tree-sha1 = "5768af7ec6a356a091ee3b189742dd0ced18d0db"
libc = "glibc"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "9cf608dd9376ac78ba2ea2155277a63a44f37597c751ad65034059bac93b2cec"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.i686-linux-gnu.tar.gz"
[[libxlsxwriter]]
arch = "i686"
git-tree-sha1 = "dea89bf1d1f065426b4d206b6ca9102c5986a39e"
libc = "musl"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "f444ca7a912ed9620cf28721198d10b0245b3fcef38995c3370f44e28c03236c"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.i686-linux-musl.tar.gz"
[[libxlsxwriter]]
arch = "powerpc64le"
git-tree-sha1 = "88683da3db0215ffb4384556a79fa37deacb425a"
libc = "glibc"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "72bdfc1f7d5d25470bf8b3c900bf09cc63ba325c3e0255cee1ed8fc03cc6d92c"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.powerpc64le-linux-gnu.tar.gz"
[[libxlsxwriter]]
arch = "riscv64"
git-tree-sha1 = "c454e8b897cba45dbef14e37dd409b0ef04c8ec7"
libc = "glibc"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "8fa07856c46ac21df30d012d9624cd7e9a314d7363e2c18a8a4b21a3be3521cf"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.riscv64-linux-gnu.tar.gz"
[[libxlsxwriter]]
arch = "x86_64"
git-tree-sha1 = "387245bc25112a0e935fd1addd810d3d52355039"
os = "macos"

    [[libxlsxwriter.download]]
    sha256 = "2e2207b6cd92ec3bf9519c3305aa344d3ddf22fc9bce1930f826ce9727ce6156"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.x86_64-apple-darwin.tar.gz"
[[libxlsxwriter]]
arch = "x86_64"
git-tree-sha1 = "17eeec3b6444669ed1e65c87ab6e986bd7769828"
libc = "glibc"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "02c90c26dc332fda5c77a99d99e10691ca5a131bbb7605d60c311ad6e814da4b"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.x86_64-linux-gnu.tar.gz"
[[libxlsxwriter]]
arch = "x86_64"
git-tree-sha1 = "7c4bf9830989d1bb9399cfcd407e86cadfa89aaf"
libc = "musl"
os = "linux"

    [[libxlsxwriter.download]]
    sha256 = "0fe80640d1a25d143e82ce8c09725d8d88d18dbc205185eb0608be3fc20e59ed"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.x86_64-linux-musl.tar.gz"
[[libxlsxwriter]]
arch = "x86_64"
git-tree-sha1 = "01c62b257d0151865c09dca8e53693ed8dc1b6ae"
os = "freebsd"

    [[libxlsxwriter.download]]
    sha256 = "ccd7091e057d25dd8e20043d7025bbd8dcaeb4b813b19a2de694c97acab27012"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.x86_64-unknown-freebsd.tar.gz"
[[libxlsxwriter]]
arch = "x86_64"
git-tree-sha1 = "42139a949d7f0be59992bfc500be1776ca9e2c55"
os = "windows"

    [[libxlsxwriter.download]]
    sha256 = "4a1e0bd91757ce6f22f3604891eb276888403c7a40beba065a526f50413f275f"
    url = "https://github.com/JuliaBinaryWrappers/libxlsxwriter_jll.jl/releases/download/libxlsxwriter-v1.2.3+0/libxlsxwriter.v1.2.3.x86_64-w64-mingw32.tar.gz"
