# Autogenerated wrapper script for libxlsxwriter_jll for aarch64-apple-darwin
export libxlsxwriter

using Zlib_jll
JLLWrappers.@generate_wrapper_header("libxlsxwriter")
JLLWrappers.@declare_library_product(libxlsxwriter, "@rpath/libxlsxwriter.7.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libxlsxwriter,
        "lib/libxlsxwriter.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
