# Autogenerated wrapper script for libxlsxwriter_jll for x86_64-w64-mingw32
export libxlsxwriter

using Zlib_jll
JLLWrappers.@generate_wrapper_header("libxlsxwriter")
JLLWrappers.@declare_library_product(libxlsxwriter, "libxlsxwriter.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libxlsxwriter,
        "bin\\libxlsxwriter.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
